/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tfe.ecole.vue;


import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JFormattedTextField;
import tfe.ecole.modele.Ouvrier;

/**
 *
 * @author yema
 */
public class AjoutOuvrierJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutChauffeurJPanell
     */
    public AjoutOuvrierJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idChauffeur = new javax.swing.JLabel();
        nomChauffeur = new javax.swing.JLabel();
        prenomChauffeur = new javax.swing.JLabel();
        AdresseChauffeur = new javax.swing.JLabel();
        dateChauffeur = new javax.swing.JLabel();
        numChauffeur = new javax.swing.JLabel();
        emailChauffeur = new javax.swing.JLabel();
        smChauffeur = new javax.swing.JLabel();
        registreNationalTextField = new javax.swing.JTextField();
        nomouvrierTextField = new javax.swing.JTextField();
        prenomTextField = new javax.swing.JTextField();
        adresseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        numTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        smTextField = new javax.swing.JTextField();
        retour = new javax.swing.JButton();
        enregistrerChauffeur = new javax.swing.JButton();
        codepostale = new javax.swing.JLabel();
        MaskFormatter mf=null;

        try{
            mf = new MaskFormatter("####");
            mf.setPlaceholderCharacter(' ');
        }
        catch (ParseException e)
        {
            System.out.println("problem de masque");
        }
        codepostaleTextField = new JFormattedTextField(mf);
        ville = new javax.swing.JLabel();
        villeTextField = new javax.swing.JTextField();

        idChauffeur.setText("registre national:");

        nomChauffeur.setText("Nom :");

        prenomChauffeur.setText("Prenom :");

        AdresseChauffeur.setText("Adresse:");

        dateChauffeur.setText("Date de naissance:");

        numChauffeur.setText("Numero de telephone:");

        emailChauffeur.setText("Email:");

        smChauffeur.setText("date visite medicale");

        registreNationalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreNationalTextFieldActionPerformed(evt);
            }
        });

        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        retour.setText("Annuler");

        enregistrerChauffeur.setText("envoyer");
        enregistrerChauffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerChauffeurActionPerformed(evt);
            }
        });

        codepostale.setText("Code postale:");

        codepostaleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codepostaleTextFieldActionPerformed(evt);
            }
        });

        ville.setText("Ville:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idChauffeur)
                            .addComponent(nomChauffeur)
                            .addComponent(prenomChauffeur)
                            .addComponent(dateChauffeur)
                            .addComponent(AdresseChauffeur)
                            .addComponent(ville))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registreNationalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomouvrierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(villeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codepostale)
                                .addGap(18, 18, 18)
                                .addComponent(codepostaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enregistrerChauffeur)
                                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numChauffeur)
                            .addComponent(smChauffeur)
                            .addComponent(emailChauffeur, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idChauffeur)
                    .addComponent(registreNationalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomChauffeur)
                    .addComponent(nomouvrierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomChauffeur)
                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChauffeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codepostale)
                    .addComponent(codepostaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresseChauffeur))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(villeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ville))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numChauffeur)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailChauffeur)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smChauffeur)
                    .addComponent(smTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retour)
                    .addComponent(enregistrerChauffeur)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerChauffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerChauffeurActionPerformed
        // TODO add your handling code here:
        Ouvrier ouvrier = new Ouvrier();
        String registreNational = registreNationalTextField.getText();
        registreNational = registreNational.replace("-", "");
        registreNational = registreNational.replace(".", "");
        if (!checkRegistreNational(registreNational)) {
            //TODO Afficher dialog d'erreur
            //Check a retourné false : Le ouvrier ne peut être créé.
            System.out.println("REGISTRE NATIONAL INCORRECT");
        } else {
            ouvrier.setId(Long.valueOf(registreNational));
            //Sinon je peux setté son attribut avec la valeur récupérée.
            System.out.println("REGISTRE NATIONAL CORRECT");
        }

        String nomChauffeur = nomouvrierTextField.getText();
        if(!VerifString(nomChauffeur)){
             System.out.println(" NOM INCORRECT");}
        else{
            
            ouvrier.setNomOuvrier(String.valueOf(nomChauffeur));
            System.out.println("NOM CORRECT");
        }

        String prenom = prenomTextField.getText();
        if(!VerifString(prenom)){
             System.out.println(" PRENOM INCORRECT");}
        else{
            
            ouvrier.setPrenomOuvrier(String.valueOf(prenomChauffeur));
            System.out.println("PRENOM CORRECT");
        }
        

        String adresse = adresseTextField.getText();
        ouvrier.setAdresse(adresse);
        
        String codepostale = codepostaleTextField.getText();
        if (!checkCodePostale(codepostale)) {
            
            System.out.println("CODE POSTALE INCORRECT");
        } else {
            ouvrier.setCodepostale(Long.valueOf(codepostale));
            
            System.out.println("CODE POSTALE CORRECT");
        }
        
         String ville = villeTextField.getText();
         VerifString(ville);
         ouvrier.setVille(ville);
        

     int numtel = numTextField.getX();
        
         ouvrier.setNumTelephone(numtel);
         
String email = emailTextField.getText();
ouvrier.setEmail(email);

         System.out.println(email );
        //TODO A faire avec tous les attributs.


        //TODO Ajouter le ouvrier à la base de données.
    }

    private boolean checkRegistreNational(String registreNational) {

        if (registreNational == null || registreNational.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        if (registreNational.length() != 11) {
            System.out.println("veuillez introduire le bon format");
            return false;
        }
        try {
            Long.valueOf(registreNational);
        } catch (NumberFormatException e) {
            System.out.println("Error");
            e.printStackTrace();
            return false;
        }
        return true;



    }//GEN-LAST:event_enregistrerChauffeurActionPerformed
     private boolean checkCodePostale(String codepostale) {

        if (codepostale == null || codepostale.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        if (codepostale.length()< '4'|| codepostale.length()<'6') {
            System.out.println("veuillez introduire le bon format");
            return false;
        }
        try {
            Long.valueOf(codepostale);
        } catch (NumberFormatException e) {
            System.out.println("Error");
            e.printStackTrace();
            return false;
        }
        return true;



    }                                                    

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void registreNationalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreNationalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registreNationalTextFieldActionPerformed

    private void codepostaleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codepostaleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codepostaleTextFieldActionPerformed

    private boolean VerifString(String caractere) {
        if (caractere == null || caractere.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        for (int i = 0; i < caractere.length(); i++) {
            if (caractere.charAt(i) == '1' || caractere.charAt(i) == '2' || caractere.charAt(i) == '3' || caractere.charAt(i) == '4'
                    || caractere.charAt(i) == '5' || caractere.charAt(i) == '6' || caractere.charAt(i) == '7' || caractere.charAt(i) == '8'
                    || caractere.charAt(i) == '9' || caractere.charAt(i) == '0') {
                System.out.println("veuillez rentrer une donnée correcte");

                return false;
            }
        }
        return true;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdresseChauffeur;
    private javax.swing.JTextField adresseTextField;
    private javax.swing.JLabel codepostale;
    private javax.swing.JTextField codepostaleTextField;
    private javax.swing.JLabel dateChauffeur;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailChauffeur;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton enregistrerChauffeur;
    private javax.swing.JLabel idChauffeur;
    private javax.swing.JLabel nomChauffeur;
    private javax.swing.JTextField nomouvrierTextField;
    private javax.swing.JLabel numChauffeur;
    private javax.swing.JTextField numTextField;
    private javax.swing.JLabel prenomChauffeur;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JTextField registreNationalTextField;
    private javax.swing.JButton retour;
    private javax.swing.JLabel smChauffeur;
    private javax.swing.JTextField smTextField;
    private javax.swing.JLabel ville;
    private javax.swing.JTextField villeTextField;
    // End of variables declaration//GEN-END:variables
}
